### ISSUE TITLE
offering config file

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout-plugins-py#20]
a .csv/ .yml/ .. file with variables that will be use in the .md to easy allow the update of the content for a new offering, examples:

- google forms link
- classroom links
- deadlines

**Comment by toshikurauchi** [comment]
Great idea! @igordsm can you take a look at this?

**Comment by igordsm** [comment]
Implementation proposal: add the possibility of adding variables in the mkdocs.yml file for the jinja template plugin #18 . It would look like this:

```
- active_handout_plugins:
  user_defined_variables:
    key1: val1
    key2: val2
```

To use in a handout: `{{ key1 }}`

thoughts @toshikurauchi @rafaelcorsi ?
